### ISSUE TITLE
Title se nazobrazuje na https://index.robotikabrno.cz/projects/elks/

### ISSUE THREAD

**Issue by jezura777** [RoboticsBrno/ProjectIndexer#8]
Nadpis v kartě se nezobrazuje na odkazu [Projekty/elks](https://index.robotikabrno.cz/projects/elks/) a na [Projekty/rbcx](https://index.robotikabrno.cz/projects/rbcx/)

Na stránce [Demo](https://index.robotikabrno.cz/demo/) se zobrazí celý link místo nadpisu, stejně jako to dělá u všech stránek s repozitáři.

**Comment by C2Coder** [comment]
Opraveno
